### ISSUE TITLE
Server Profile Template and Server Profile description are not set

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#369] opened 2021-08-05 09:45 UTC
## Scenario/Intent

When doing a terraform apply to create the Server Profile Template resource, the SPT and SP description parameters are not taken into account. Both parameters are declared and set respectively in the variables.tf and variables.tfvars files.

However, the SPT resource that is created doesn't have those fields configured on OneView.

In the OneView REST api, the fields are spt.description and spt.serverProfileDescription.

## Environment

- terraform oneview provider: v6.2
- OneView api version : 2800

## Expected Result

After setting the SPT and SP descriptions in the tfvars file and doing a `terraform apply -var-file=variables.tfvars`, the SPT resource created has those field configured in OneView. 

## Actual result

SPT and SP descriptions are not set.

**Comment by nabhajit-ray** [comment] 2021-08-09 07:26
Thanks for pointing this out. We will fix this with 6.30 release

**Comment by nabhajit-ray** [comment] 2021-08-24 04:22
Hi Claire,

The issue is fixed in master branch. It will be available in registry with OV 6.3 release

**Closed by nabhajit-ray** 2021-08-24 04:22 UTC
