### ISSUE TITLE
Terraform crashes on Logical Enclosure create

### ISSUE THREAD

**Issue by wayno123** [HewlettPackard/terraform-provider-oneview#288] opened 2021-03-31 16:41 UTC
I just experienced a Terraform crash. 
$terraform --version
Terraform v0.12.30
+ provider.oneview (unversioned)

Synergy on DCS simulator 5.40 (2000)

The final step in my terraform apply was to create a new Logical Enclosure. After 28 minutes Terraform crashed, but the Logical Enclosure and associated Logical Interconnects completed successfully as seen in OneView.

`Terraform will perform the following actions:
...
  # oneview_logical_enclosure.LogicalEnclosure-prod will be created
  + resource "oneview_logical_enclosure" "LogicalEnclosure-prod" {
      + enclosure_group_uri = "/rest/enclosure-groups/03a7478f-1045-430b-995d-99ad8bbdfc9a"
      + enclosure_uris      = [
          + "/rest/enclosures/0000000000A66101",
          + "/rest/enclosures/0000000000A66102",
          + "/rest/enclosures/0000000000A66103",
        ]
      + id                  = (known after apply)
      + name                = "LE-prod"
    }
...
oneview_logical_enclosure.LogicalEnclosure-prod: Still creating... [30s elapsed]
oneview_logical_enclosure.LogicalEnclosure-prod: Still creating... [40s elapsed]
oneview_logical_enclosure.LogicalEnclosure-prod: Still creating... [50s elapsed]
...
oneview_logical_enclosure.LogicalEnclosure-prod: Still creating... [28m10s elapsed]
oneview_logical_enclosure.LogicalEnclosure-prod: Still creating... [28m20s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!`

Adding full screen capture and crash.log. Let me know if you require additional info.
WC
[Terraform-crash-LE-build-screen-stdout.txt](https://github.com/HewlettPackard/terraform-provider-oneview/files/6238096/Terraform-crash-LE-build-screen-stdout.txt)
[crash.log](https://github.com/HewlettPackard/terraform-provider-oneview/files/6238098/crash.log)

**Comment by nabhajit-ray** [comment] 2021-04-07 17:27
Hi Wayne,

I am not able to reproduce the issue.My LE creation is successful without any crash. The crash.log  you shared points to deploymentManagerSettings attributes of LE. Can you share the JSON payload of the LE that got created?You can use postman client to do a GET operation on the LE.

**Comment by nabhajit-ray** [comment] 2021-04-07 17:30
Also , please share your configuration file(tf file).

**Comment by nabhajit-ray** [comment] 2021-04-14 08:05
@wayno123  Can you please share the JSON payload of the LE and your configuration files?

**Comment by wayno123** [comment] 2021-04-15 17:32
[Oneview-Terraform-crash-files.tar.gz](https://github.com/HewlettPackard/terraform-provider-oneview/files/6320045/Oneview-Terraform-crash-files.tar.gz)

Here is my main.tf, variables.tf, outputs.tf, and terraform.tfstate files. Let me know if you need other files. (Attached)

terraform --version
Terraform v0.12.30

terraform-provider-oneview-6.0.0-12

**Comment by nabhajit-ray** [comment] 2021-04-23 03:56
@wayno123: Can you please check if the issue is resolved?

**Comment by nabhajit-ray** [comment] 2021-05-13 05:07
Closing this as of now. Please reopen if it is still reproducible

**Closed by nabhajit-ray** 2021-05-13 05:07 UTC
