### ISSUE TITLE
firmware attribute not updating

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#407] opened 2021-09-28 19:40 UTC
on server profile template, if a template is created without a firmware_install_type set, and then you modify it to  something different like firmware_install_type = "FirmwareOnlyOfflineMode"  I don't believe it does anything.  It just reports green, 0 changes.

**Comment by nabhajit-ray** [comment] 2021-09-29 09:51
Not able to reproduce it.
tf content:
 firmware {
    force_install_firmware   = false
    firmware_baseline_uri    = "/rest/firmware-drivers/ssd"
    firmware_activation_type = "Immediate"
    manage_firmware          = true   
    compliance_control       = "Unchecked"
  }

terraform plan output after adding firmware_install_type:

  ~ firmware {
            compliance_control       = "Unchecked"
            firmware_activation_type = "Immediate"
            firmware_baseline_uri    = "/rest/firmware-drivers/ssd"
          ~ firmware_install_type    = "FirmwareAndOSDrivers" -> "FirmwareOnlyOfflineMode"
            force_install_firmware   = false
            manage_firmware          = true
        }


Please share your configuration

**Comment by nabhajit-ray** [comment] 2021-10-04 05:30
Hi Rismoney, we have not heard from you. If it is working for you please close the issue.

**Comment by nabhajit-ray** [comment] 2021-10-06 04:11
As we have not heard back on the issue, we assume that it is resolved. Feel free to reopen if you need further help/clarification.

**Closed by nabhajit-ray** 2021-10-06 04:11 UTC
