### ISSUE TITLE
Interconnect Link Topology error - creating logical enclosure

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#431] opened 2021-11-15 14:42 UTC
## Scenario/Intent

Hello,

When we try to create the logical enclosure we have an error on the topology which we don't have when creating the LE manually.
The configuration used in both case is the same.

The networks, logical interconnect groups and enclosure group are created without error beforehand.

## Environment Details

- OneView Terraform SDK provider: v6.3.1-13
- OneView Appliance Version: 6.10

## Expected Result

The logical enclosure is created.

## Actual Result

```
Error: The specified enclosures do not completely describe membership of a single interconnect link topology (ILT).
Verify that interconnect link cables are connected to form a single interconnect link topology (ILT). If the interconnect link cables are connected properly, specify an enclosure list that matches the membership of an ILT as defined in the enclosure group.
The enclosure list must have the same number of enclosures in the same order as the ILT. ILTs can be retrieved using the /rest/interconnect-link-topologies API.
```

**Comment by nabhajit-ray** [comment] 2021-11-25 04:11
Hi Claire, Can you try it out with the new version 6.4.0-13 since it was not reproducible with the master branch plugin.

**Comment by ClaireHayard** [comment] 2021-11-26 10:21
Hello Nabhajit, I did not encounter the problem when using the master branch plugin. When we re-ran the code with the lastest version ,this error did not pop up.

**Comment by nabhajit-ray** [comment] 2021-11-29 04:54
Closing this as it is not reproducible

**Closed by nabhajit-ray** 2021-11-29 04:54 UTC
