### ISSUE TITLE
netset update networks described in plan not correct?

### ISSUE THREAD

**Issue by rismoney** [HewlettPackard/terraform-provider-oneview#499] opened 2022-09-30 13:48 UTC
this is a cosmetic issue in the plan/output.

When you add a network to an existing netset, (it works) but the tf apply seems to indicate a "-" next to the the existing networks, leading you to believe there will be network deletions from the netset, but that is not the case.  It does work and does the right thing, but just wanted to raise awareness.

let me know if you need screengrabs or more info.

**Comment by nabhajit-ray** [comment] 2022-10-03 05:06
We will look into this and back to you

**Comment by nabhajit-ray** [comment] 2022-10-04 06:25
Hi @rismoney ,

Not able to reproduce. We are getting below 


` Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the ` ` ` 
  following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # oneview_network_set.NetworkSet will be updated in-place
  ~ resource "oneview_network_set" "NetworkSet" {
        id                      = "TestNetworkSet"
        name                    = "TestNetworkSet"
      - network_set_type        = "Regular" -> null
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.



Please share the screenshot and the configuration file

**Comment by nabhajit-ray** [comment] 2022-10-27 07:03
Did not hear from you. Closing it here. Please it

**Closed by nabhajit-ray** 2022-10-27 07:03 UTC
