### ISSUE TITLE
Issue applying Connection_settings attributes when creating server templates

### ISSUE THREAD

**Issue by josyfj** [HewlettPackard/terraform-provider-oneview#474] opened 2022-04-25 15:08 UTC
Issue: When attempting to create a server template with local storage san, we get the following error: 

```
│ Error: The attachment (ID = 1) has a storage path that refers to connection (ID = 1) that does not exist on the profile. 
│ Remove the storage path, or change the connection ID to correspond to a valid connection on the profile.
│
│   with module.Add_Server_Templates.oneview_server_profile_template.ServerProfileTemplateWithSanStorage,
│   on 06_Server_Templates\main.tf line 26, in resource "oneview_server_profile_template" "ServerProfileTemplateWithSanStorage":
│   26: resource "oneview_server_profile_template" "ServerProfileTemplateWithSanStorage" {
│
╵
```

Code for the resource below:

```
resource "oneview_server_profile_template" "ServerProfileTemplateWithSanStorage" {
  name                 = "NewTestServerTemplate_with_local_storage_san"
  type                 = "ServerProfileTemplateV8"
  #enclosure_group      = "EG"
  server_hardware_type = "DL360 Gen10 1"
  initial_scope_uris   = [data.oneview_scope.scope.uri]
  connection_settings {
    manage_connections = false
    compliance_control = "CheckedMinimum"
    connections {
      id             = 1
      name           = "SAN_A"
      function_type  = "FibreChannel"
      #port_id        = "Mezz 3:1-b"
      #requested_mbps = 2500
      network_uri    = data.oneview_fc_network.fcNetwork1.uri
    boot {
        priority           = "Primary"
        ethernet_boot_type = "PXE"
      }
    }
  }
  san_storage {
    host_os_type       = "VMware (ESXi)"
    manage_san_storage = true
  }
  volume_attachments {
    boot_volume_priority      = "NotBootable"
    id                        = 1
    lun_type                  = "Auto"
    volume_storage_system_uri = “<volume_storage-system-uri>”
    volume_uri                = “<volume_uri>”
    storage_paths {
      connection_id   = 1
      network_uri     = "<Network_uri>"
      target_selector = "Auto"
      is_enabled      = true
    }
}
}
```
We are able to force the resource to work if we set the manage_san_storage to false, however for our application we require that manage_san_storage be set to true. 

Can you provide assistance as to why we are getting this error and what can be done to circumvent it?

**Comment by nabhajit-ray** [comment] 2022-05-30 05:29
Hi @josyfj ,

We will look into this and get back to you.
Thanks

**Comment by nabhajit-ray** [comment] 2022-06-20 06:19
Hi @josyfj ,

While we could not reproduce the issue , we have made some fix to the SPT creation and also added examples to create SPT with SAN storage.  You can try the below example:
``
##Creates server profile template with san storage for DL server with existing volume
resource "oneview_server_profile_template" "ServerProfileTemplateWithSanStorage" {
  name = "TestServerProfileTemplate_with_local_storage_san2"
  type = "ServerProfileTemplateV8"
  //enclosure_group      = "EG"
  server_hardware_type = "DL360 Gen10"
  initial_scope_uris   = [data.oneview_scope.scope.uri]
  bios_option {
    manage_bios = false
  }
  boot {
    boot_order         = []
    compliance_control = "Unchecked"
    manage_boot        = false
  }
  boot_mode {
    manage_mode     = true
    mode            = "UEFIOptimized"
    pxe_boot_policy = "Auto"
    secure_boot     = "Unmanaged"
  }
  connection_settings {
    manage_connections = true
    compliance_control = "Checked"
    connections {
      id             = 1
      isolated_trunk = false
      name           = "connection1"
      function_type  = "FibreChannel"
      #port_id        = "Pci 1:1"
      network_uri = data.oneview_fc_network.fcNetwork.uri
    }
  }
  san_storage {
    host_os_type       = "Windows 2012 / WS2012 R2"
    manage_san_storage = true
  }  
  volume_attachments {
    boot_volume_priority      = "NotBootable"
    id                        = 1
    is_permanent              = true
    lun_type                  = "Auto"
    volume_storage_system_uri = "/rest/storage-systems/TXQ1000307"
    volume_uri                = "/rest/storage-volumes/75FE3A14-7045-47E4-A760-AEAD00718827"
    storage_paths {
      connection_id   = 1
      network_uri     = "/rest/fc-networks/81f84e14-91ee-4b88-a2af-defd12add74f"
      target_selector = "Auto"
      is_enabled      = true
    }
  }
}``

**Comment by nabhajit-ray** [comment] 2022-06-30 09:46
Closing it here as it is fixed in master branch

**Closed by nabhajit-ray** 2022-06-30 09:46 UTC
