### ISSUE TITLE
Adding DLs servers in OneView fails

### ISSUE THREAD

**Issue by ClaireHayard** [HewlettPackard/terraform-provider-oneview#414] opened 2021-10-06 14:40 UTC
## Scenario/Intent

Hello,

I am adding some DLs servers in my OneView appliance with their hostname but it ends with an error.
Suprisingly, the server hardwares are still added in the OneView.

## Environment Details

- OneView Terraform SDK provider: v6.3.0-13 (build manually from the master branch)
- OneView Appliance Version: 6.30

## Expected Result

The DLs servers are added in the OneView appliance.

## Actual Result
 
```
err: unable to retrieve server hardware %!s(<nil>)
```

**Comment by ClaireHayard** [comment] 2021-10-13 12:44
Hello @nabhajit-ray,

I tried to change the value of the `licensing_intent   = "OneView"` to `OneViewNoiLO` but I get the same error as above.

**Comment by nabhajit-ray** [comment] 2021-10-14 05:10
Can you import the resource and share the output of tfstate file.

**Comment by nabhajit-ray** [comment] 2021-11-08 10:00
The issue is fixed in master. Please check and let us know

**Closed** 2021-11-19 13:41 UTC
