### ISSUE TITLE
Adding/Removing/Updating an uplinkset to a LIG will also modify the whole LIG

### ISSUE THREAD

**Issue by odesaphy** [HewlettPackard/terraform-provider-oneview#467] opened 2022-03-25 10:56 UTC
When I add a new uplinkset (testuplinkset)to an existing LIG with terragrunt/terraform, the following actions are done :

![image](https://user-images.githubusercontent.com/25363168/160108009-6789f802-694c-4ae4-b9a4-2799835782b5.png)

If I'm doing it with the GUI 
![image](https://user-images.githubusercontent.com/25363168/160108167-05e44e46-78e2-4cae-af49-ccdad57263cf.png)

Same behaviour when Removing or Updating an uplinkset

**Comment by Lanata07** [comment] 2022-06-14 13:26
Any updates regarding this issue ?

**Comment by nabhajit-ray** [comment] 2022-06-15 05:28
We are able reproduce the issue. Regardiing the fix we will check and get back on this.

**Comment by nabhajit-ray** [comment] 2022-09-09 05:11
Hi @Lanata07 ,

We tested and verified the fix and it is working in our environment. Please share the configuration that you are going to run , so that we can check it.
Thanks,

**Comment by odesaphy** [comment] 2022-09-13 14:09
I've tested with latest provider 7.2.0-0.13 and there are still issues :

- My terragrunt/terraform code will not work with OneView 6.10 for Synergy (apiVersion=2800) when creating the LIGs : 

```
oneview_logical_interconnect_group.LIG["lig3pbga04b07"]: Creating...

Error: Error in response: Unrecognized JSON field.
 Response Status: 400 Bad Request
 Response Details: The field named dcbxOverride near line 1, column 1,230 is not a valid field in this JSON object.
```
dcbxOverride has been added in OneView 6.30

- Testing with OneView 6.30 for Synergy (apiVersion = 3200)

**Adding a new uplinkset on a LIG :** 
![image](https://user-images.githubusercontent.com/25363168/189919822-ee03059b-4c27-4db1-9aa8-7471040fcf6c.png)

**Removing an uplinkset on a LIG :** 
![image](https://user-images.githubusercontent.com/25363168/189920274-f3255ac6-6aac-4843-97cb-53a6268242cd.png)

**Modifying an uplinkset on a LIG: **
![image](https://user-images.githubusercontent.com/25363168/189923284-61c1c749-817d-49b9-9f00-075c9d1cdeba.png)

The NTP configuration is modified when adding/removing/modifying an uplinkset

Beware : the newly uplinkset must be added at the end of the uplinkset list in our terragrunt.hcl 

Versions : 
```
terraform --version
Terraform v0.13.7

terragrunt --version
terragrunt version v0.36.11
```

**Comment by nabhajit-ray** [comment] 2022-09-14 05:56
Hi @odesaphy ,

We are not getting NTP configuration getting changed during update. Can you share the LIG configuration file you are using to create the LIG and what new uplink set you are adding ,so that we can reproduce the issue locally?

**Comment by nabhajit-ray** [comment] 2022-09-19 05:21
Can you please share the steps for LIG creation along with NTP configuration?

**Comment by nabhajit-ray** [comment] 2022-11-16 04:49
Closing this ,since we did not hear from you. Please open another defect if there is any issue.

**Closed by nabhajit-ray** 2022-11-16 04:49 UTC
