### ISSUE TITLE
Assigning a WWPN when applying a server profile from a template

### ISSUE THREAD

**Issue by josyfj** [HewlettPackard/terraform-provider-oneview#475] opened 2022-04-25 15:10 UTC
Issue: When applying a server profile from a template, we are unable to add a WWPN, which causes the apply to fail. 

Affected resource: 

```
resource "oneview_server_profile" "server_profile" {
  name = "My_Test_Profile"
  template = "Terraform_Test_Template"
  hardware_name = "<Server_hardware_name>"
  connection_settings {
      connections{
        name = "<network_name>"
        port_id = "1"
        network_uri = <network_uri>"
        wwpn = "<wwpn>"
      }
  }
}
```

Error message:

```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.Add_Profile.oneview_server_profile.server_profile, provider
│ "provider[\"registry.terraform.io/hewlettpackard/oneview\"]" produced an unexpected new value: Root resource was present, but   
│ now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

Expected output: The server profile is applied using the proper connection and connection settings.

**Comment by nabhajit-ray** [comment] 2022-05-26 08:37
Hi @josyfj ,

Please share your server profile configuration and with attribute values wherever possible.

**Comment by nabhajit-ray** [comment] 2022-06-01 09:42
Hey @josyfj ,

One quick query, are you having any hostname for your server hardware?  In OneView GUI can you check whether the server hardware name is having the iLO ipaddress or the iLO hostname?

**Comment by josyfj** [comment] 2022-06-01 10:14
Hello @nabhajit-ray ,

We are using the IP address in this case. There is no hostname currently.

**Comment by nabhajit-ray** [comment] 2022-06-14 08:09
Hi @josyfj ,

As discussed we are not able to reproduce the issue. So it would be helpful if you can share the terraform configuration file used by you.
Thanks,

**Comment by nabhajit-ray** [comment] 2022-06-30 09:39
Since no reponse was received, Closing it now.

**Closed by nabhajit-ray** 2022-06-30 09:39 UTC
