### ISSUE TITLE
oneview_logical_interconnect_group Data Source returns null Data

### ISSUE THREAD

**Issue by bigmagic** [HewlettPackard/terraform-provider-oneview#353] opened 2021-07-12 08:20 UTC
Hi,

In the Terraform code, we are getting the data source of oneview_logical_interconnect_group  but we are getting null values.

We are using the following versions:

- version of Terraform :

```
$ terraform --version
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hewlettpackard/oneview v6.1.0-13

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from https://www.terraform.io/downloads.html
```
- version of OneView:  6.10.00-0436703

You will find an example code :

```
$ cat main.tf
locals {
  lig_list = [
    "LIG2VC100PAB07",
    "LIG3VC100PAB07"
  ]
}

terraform {
  required_providers {
    oneview = {
      source  = "HewlettPackard/oneview"
      version = "6.1.0-13"
    }
  }
}

provider "oneview" {
  ov_username   = var.oneview_username
  ov_password   = var.oneview_password
  ov_endpoint   = var.oneview_uri
  ov_sslverify  = var.ssl_enabled
  ov_apiversion = var.oneview_apiversion
  ov_ifmatch    = "*"
}

data "oneview_logical_interconnect_group" "LIG" {
  for_each = { for lig in local.lig_list : lig => lig }
    name = each.value
}

output "debug" {
    value = data.oneview_logical_interconnect_group.LIG
}

```

Below the trace of the execution:

```
$ TF_LOG=trace terraform plan -var-file=variables.tfvars
2021-07-12T08:16:36.970Z [TRACE] setValue: Saving Create change for output.debug in changeset
2021-07-12T08:16:36.970Z [TRACE] setValue: Saving value for output.debug in state
**2021-07-12T08:16:36.976Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"**

Changes to Outputs:
  + debug = {
      + LIG2VC100PAB07 = {
          + category                        = null
          + created                         = null
          + description                     = null
          + enclosure_indexes               = null
          + etag                            = null
          + fabric_uri                      = null
          + id                              = null
          + igmp_settings                   = null
          + interconnect_bay_set            = null
          + interconnect_map_entry_template = null
          + interconnect_settings           = null
          + internal_network_uris           = null
          + modified                        = null
          + name                            = null
          + port_flap_settings              = null
          + quality_of_service              = null
          + redundancy_type                 = null
          + sflow_configuration             = null
          + snmp_configuration              = null
          + state                           = null
          + status                          = null
          + telemetry_configuration         = null
          + type                            = null
          + uplink_set                      = null
          + uri                             = null
        }
      + LIG3VC100PAB07 = {
          + category                        = null
          + created                         = null
          + description                     = null
          + enclosure_indexes               = null
          + etag                            = null
          + fabric_uri                      = null
          + id                              = null
          + igmp_settings                   = null
          + interconnect_bay_set            = null
          + interconnect_map_entry_template = null
          + interconnect_settings           = null
          + internal_network_uris           = null
          + modified                        = null
          + name                            = null
          + port_flap_settings              = null
          + quality_of_service              = null
          + redundancy_type                 = null
          + sflow_configuration             = null
          + snmp_configuration              = null
          + state                           = null
          + status                          = null
          + telemetry_configuration         = null
          + type                            = null
          + uplink_set                      = null
          + uri                             = null
        }
    }

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

--------------------------------------------------------------------------------------------------------------------------

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you
run "terraform apply" now.
**2021-07-12T08:16:36.976Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hewlettpackard/oneview/6.1.0-13/linux_amd64/terraform-provider-oneview_v6.1.0-13 pid=17844
2021-07-12T08:16:36.977Z [DEBUG] provider: plugin exited**
2021-07-12T08:16:36.977Z [TRACE] setValue: Saving Create change for output.debug in changeset
2021-07-12T08:16:36.978Z [TRACE] setValue: Saving value for output.debug in state
2021-07-12T08:16:36.978Z [TRACE] vertex "output.debug": visit complete
2021-07-12T08:16:36.978Z [TRACE] vertex "meta.count-boundary (EachMode fixup)": starting visit (*terraform.NodeCountBoundary)
2021-07-12T08:16:36.978Z [TRACE] vertex "meta.count-boundary (EachMode fixup)": visit complete
2021-07-12T08:16:36.978Z [TRACE] vertex "provider[\"registry.terraform.io/hewlettpackard/oneview\"] (close)": visit complete
2021-07-12T08:16:36.978Z [TRACE] vertex "root": starting visit (*terraform.nodeCloseModule)
2021-07-12T08:16:36.978Z [TRACE] vertex "root": visit complete
2021-07-12T08:16:36.978Z [INFO]  backend/local: plan operation completed
2021-07-12T08:16:36.980Z [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021-07-12T08:16:36.981Z [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock

```

It seems that the provider is crashing.

I thank you for a fix,

Best Regards,
Nicolas

**Comment by nabhajit-ray** [comment] 2021-07-14 12:43
Hi Nicolas,

We have checked this and there is a minor mistake in our datasource file. The fix of which will be posted soon. Having said that, we are not supportng Terraform verison 1.0 yet. Currently we are supporting version 0.13

**Comment by nabhajit-ray** [comment] 2021-07-19 04:27
Hi Nicolas, Please check with latest master branch and let us know if the issue is resolved

**Comment by nabhajit-ray** [comment] 2021-07-28 11:32
Hi Nicolas ,  I am closing this defect as of now. Feel free to re-open if it is still not resolved.

**Closed** 2021-07-28 11:32 UTC
