### ISSUE TITLE
Documentation and Links are dead

### ISSUE THREAD

**Issue by madpat1998** [HewlettPackard/terraform-provider-oneview#529] opened 2023-05-05 14:07 UTC
Most links in README are dead and the documentation on terraform registry is empty.

**Comment by nabhajit-ray** [comment] 2023-05-08 10:42
Thanks for the feedback. Will work on this.

**Comment by nabhajit-ray** [comment] 2023-06-05 06:03
The issue is fixed  in the main branch. Closing it here.

**Closed by nabhajit-ray** 2023-06-05 06:03 UTC
