### ISSUE TITLE
Ethernet Networks Allow uplinkset assignment

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#44] opened 2018-02-23 14:58 UTC
Hi,

Can you advise whether it is going to be possible to assign the uplink set as part of the ethernet network generation?

Cheers

**Comment by jsmartt** [comment] 2018-02-23 17:12
@wingZero21, you should be able to assign the ethernet network to a LIG uplink set (see the example [here](https://github.com/HewlettPackard/terraform-provider-oneview/blob/master/docs/r/logical_interconnect_group.html.markdown)). Is that what you are looking for?

**Comment by wingZero21** [comment] 2018-02-26 07:31
Hi,

Yes I can see if possible to assign if we configure the LIG setup. However currently when assigning the vlans via virtual connect in the below example, it allows you to just assign the uplink set as part of the initial vlan creation.

Is this something that might be added in the future so it is matching what it previously was in virtual connect? Is this a current limitation within the current version of oneview?

Cheers
Details:
EG: Current virtual connect add vlan
```
add  network  network-vlan-A-4000  UplinkSet=UPLINK-A  VLanID=4000
```

**Comment by jsmartt** [comment] 2018-02-26 16:00
Assigning a network to an uplink requires a separate API call from creating the network. Since we're dealing with 2 different resources, we basically have 2 options in describing them in Terraform. Either the network can reference the LIG uplink set, or the LIG uplinks set can reference the uplink set. The problem with the network referencing the LIG uplink set is that uplink set names need not be globally unique. This presents an issue when using code like you have above; `UPLINK-A` could match more than one uplink set.

So, there's more than one way to do it, but I believe the way provided with Terraform presents the least opportunity for unexpected behavior. It's easier to implement this way too, since it more closely matches the API resource model.

I hope that provides more clarity

**Comment by AsisBagga** [comment] 2020-08-12 12:57
@wingZero21 Hi, Let us know if you have any further question before we close this issue. Thanks.

**Comment by AsisBagga** [comment] 2020-08-19 14:57
Hi, Since we haven't received any updates, ill proceed with closing this issue.
If you still have any query, you can let us know by opening a new issue, we will be glad to assist. Thanks.

**Closed by AsisBagga** 2020-08-19 14:57 UTC
Labels: question
